export enum ResponseCodes {
  ok,
  error,
  unauthorized,
  too_many_login,
  token_invalid,
  missing_signature_or_addresss,
  signature_verification_failed,
  user_not_found,
  dog_not_found,
  land_not_found,
  challenge_not_found,
  card_not_found,
  dog_ai_clazz_not_found,
  dog_not_meet_requirement,
  reward_not_found,
  id_invalid,
  checksum_invalid,
  parameter_invalid,
  card_gender_invalid,
  token_missing_or_invalid,
  item_not_found,
  must_feed_item,
  not_enough_energy,
  can_not_breed_this_time,
  email_or_password_is_wrong,
  missing_checksum,
  training_not_found,
  cant_active_quest,
  cant_complate_quest,
  user_quest_not_found,
  not_allow,
  enrgy_shop_not_found,
  must_equipment_item,
  user_name_not_empty,
  user_name_duplicate,
  user_name_not_less_than_6_and_greater_than_12,
  match_id_not_found,
  match_id_required,
  game_end,
  token_not_enough_change_name,
  user_quest_not_completed,
  the_dog_ate_this_food,
  code_training_not_found,
  game_feature_not_active,
}

export const ErrorMessages = new Map([
  [ResponseCodes.error, "Something error during process the request"],
  [
    ResponseCodes.missing_signature_or_addresss,
    "Request should have signature and public_addres",
  ],
]);
